fix: update action SD-373

diff --git a/.github/actions/build-image/action.yaml b/.github/actions/build-image/action.yaml
--- a/.github/actions/build-image/action.yaml
+++ b/.github/actions/build-image/action.yaml
@@ -14,6 +14,14 @@ inputs:
   context:
     description: folder with files required to build docker image
     required: true
+  dockerhub_registry_url:
+    description: dockerhub api registry url
+    required: false
+    default: https://registry.hub.docker.com/v2
+  dockerhub_token_url:
+    description: dockerhub api token url
+    required: false
+    default: https://hub.docker.com/v2/users/login/
   dockerhub_token:
     description: token for read-only access to dockerhub
     required: false
@@ -36,37 +44,29 @@ inputs:
 runs:
   using: composite
   steps:
-    - name: Combine all .env files into .env.common file
-      id: env-files
-      uses: ftnext/action-concatenate-files@v1.0.1
+    - name: Export environment variables from .env files
+      id: env-vars
+      uses: aarcangeli/load-dotenv@v1
       with:
-        sources: |
+        filenames: |
           .env
           .env.${{ inputs.environment }}
           ${{ inputs.context }}/.env
           ${{ inputs.context }}/.env.${{ inputs.environment }}
-        destination: .env.common
-    - name: Export environment variables from .env.common file
-      id: env-common
-      uses: c-py/action-dotenv-to-setenv@v5
-      with:
-        env-file: .env.common
     - name: Configure AWS credentials
       id: aws-credentials
-      uses: aws-actions/configure-aws-credentials@v4.3.1
+      uses: aws-actions/configure-aws-credentials@v5.0.0
       with:
         aws-region: ${{ env.aws_region }}
         role-to-assume: ${{ env.aws_gha_role }}
     - name: Login to AWS ECR
       id: ecr
       uses: aws-actions/amazon-ecr-login@v2.0.1
-    - name: Find the tag for a given image digest
-      id: tag
+    - name: Get DockerHub API token
+      id: dockerhub-token
       shell: bash
       run: |
-        target_digest=$(grep '^ARG IMAGE_SHA=' ${{ inputs.context }}/Dockerfile | cut -d= -f2)
-        echo "Image digest: ${target_digest}"
-
+        set -euo pipefail
         # get dockerhub authorization token
         # if the dockerhub username and password isn't passed, then we get the following response:
         # {"detail":"Incorrect authentication credentials"}
@@ -74,17 +74,26 @@ runs:
         token=$(curl -X POST \
           -s -H "Content-Type: application/json" \
           -d "{\"username\": \"${{ inputs.dockerhub_username }}\", \"password\": \"${{ inputs.dockerhub_token }}\"}" \
-          https://hub.docker.com/v2/users/login/ | jq -r '.token // empty')
+          ${{ inputs.dockerhub_token_url }} | jq -r '.token // empty')
+        echo "token=${token}" >> $GITHUB_OUTPUT
+    - name: Find the tag for a given image digest in Dockerhub
+      id: tag
+      shell: bash
+      run: |
+        set -euo pipefail
+        target_digest=$(grep '^ARG IMAGE_SHA=' ${{ inputs.context }}/Dockerfile | cut -d= -f2)
+        echo "Image digest: ${target_digest}"
 
         # find a tag whose digest matches the given one and which is not called 'latest'
         page=1
         block_size=50
-        url="https://registry.hub.docker.com/v2/repositories/${docker_repository}/tags"
+        url="${{ inputs.dockerhub_registry_url }}/repositories/${docker_repository}/tags"
         total_tags=$(curl -s ${url} | jq -r '.count')
+        tag=""
         while [[ -z ${tag} && ${page} -le ${total_tags} ]]; do
           # the authorization token is added to the request if it has a non-empty value
           tag=$(curl \
-            -s ${token:+-H "Authorization: JWT ${token}"} \
+            -s ${token:+-H "Authorization: JWT ${{ steps.dockerhub-token.outputs.token }}"} \
             "${url}?page_size=${block_size}&page=${page}" \
             | jq -r --arg digest "${target_digest}" \
             '.results // [] | .[] | select(.digest == $digest and .name != "latest") | .name')
@@ -104,19 +113,12 @@ runs:
         platforms: ${{ env.platforms }}
         push: true
         tags: ${{ env.ecr_repository_uri }}:${{ steps.tag.outputs.image_tag }}, ${{ env.ecr_repository_uri }}:latest
-    - name: Configure settings for slack message and PR comment
-      id: data
+    - name: Configure settings for PR comment
+      id: pr-data
       if: ${{ !cancelled() }}
       shell: bash
       run: |
-        if ${{ contains(steps.*.outcome, 'failure') }}; then
-          echo "color=cc0000" >> $GITHUB_OUTPUT
-          echo "message=😞 The build of *${{ inputs.context }}* image failed." >> $GITHUB_OUTPUT
-        else
-          echo "color=28a745" >> $GITHUB_OUTPUT
-          echo "message=The build of *${{ inputs.context }}* image with version *${{ steps.tag.outputs.image_tag }}* was successful! :rocket:" >> $GITHUB_OUTPUT
-        fi
-
+        set -euo pipefail
         # create json file name with variables for pr comment using context name
         # `buildpacks/backend/builder` --> `buildpacks-backend-builder`
         artifact="${{ inputs.context }}"
@@ -149,8 +151,20 @@ runs:
       if: ${{ !cancelled() }}
       uses: actions/upload-artifact@v4
       with:
-        name: ${{ steps.data.outputs.artifact }}
-        path: ${{ steps.data.outputs.artifact }}.json
+        name: ${{ steps.pr-data.outputs.artifact }}
+        path: ${{ steps.pr-data.outputs.artifact }}.json
+    - name: Configure settings for slack message
+      id: slack-data
+      if: ${{ !cancelled() }}
+      shell: bash
+      run: |
+        set -euo pipefail
+        if ${{ contains(steps.*.outcome, 'failure') }}; then
+          echo "color=cc0000" >> $GITHUB_OUTPUT
+          echo "message=😞 The build of *${{ inputs.context }}* image failed." >> $GITHUB_OUTPUT
+        else
+          echo "color=28a745" >> $GITHUB_OUTPUT
+        fi
     - name: Send notification to slack
       if: ${{ !cancelled() }}
       uses: slackapi/slack-github-action@v2.1.1
@@ -159,13 +173,13 @@ runs:
         webhook-type: incoming-webhook
         payload: |-
           attachments:
-            - color: "${{ steps.data.outputs.color }}"
+            - color: "${{ steps.slack-data.outputs.color }}"
               author_name: ${{ github.actor }}
               author_link: https://github.com/${{ github.actor }}
               author_icon: https://github.com/${{ github.actor }}.png
               fields:
                 - short: false
-                  value: "${{ steps.data.outputs.message }}"
+                  value: "${{ steps.slack-data.outputs.message }}"
                 - title: Environment
                   short: true
                   value: ${{ inputs.environment }}
@@ -175,3 +189,6 @@ runs:
                 - title: Action URL
                   short: true
                   value: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.job }}>
+                - title: Repository
+                  short: true
+                  value: <https://github.com/${{ github.repository }}/blob/main/${{ inputs.context }}/Dockerfile|${{ github.repository }}>
